version: "3.7"

services:
  database:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - database-volume:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyplanet
      MYSQL_USER: pyplanet
      MYSQL_PASSWORD: pyplanet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute="SHOW DATABASES;"
      interval: 60s
      timeout: 2s
      retries: 1
      start_period: 15s
    networks:
      - server-network
  server:
    build:
      context: ../../build-server
    image: trackmania-server-docker:insalan-server
    restart: on-failure
    depends_on:
      - database
    environment:
      SERVER_TITLE: "Trackmania"
      SERVER_NAME: "Insalan Cup1"
    ports:
      - "2351:2351/tcp"
      - "2351:2351/udp"
    #      - "3450:3450/tcp"
    #      - "3450:3450/udp"
    expose:
      - 5005
    volumes:
      - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml:Z
      - ../maps:/home/server/tm_server/UserData/Maps:z
      - ./maps/MatchSettings:/home/server/tm_server/UserData/Maps/MatchSettings:z
    networks:
      - server-network
  controller:
    image: harha/trackmania-server-docker:pyplanet
    restart: on-failure
    depends_on:
      - database
      - server
    volumes:
      - ../pyplanet/settings:/home/server/pyplanet/settings:Z
      - ../maps:/home/server/tm_server/UserData/Maps:z
      - ./maps/MatchSettings:/home/server/tm_server/UserData/Maps/MatchSettings:z
    networks:
      - server-network

networks:
  server-network:
    driver: bridge

volumes:
  database-volume:
    driver: local
